services:
  # Trigger Redeploy: 2024-04-02 12:56
  - type: web
    name: prefeitura-digital-backend
    env: python
    region: ohio
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: mysql+pymysql://admin:adminpassword@mysql-db:3306/leopoldina
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "60"
      - key: OPENAI_API_KEY
        sync: false
      - key: ZAPI_INSTANCE_ID
        value: "3F3BF8CBA41E3168C899B26D6B588ED8"
      - key: ZAPI_TOKEN
        value: "2FBDDE3FEA7EC43E8AE0E0C8"
      - key: ZAPI_CLIENT_TOKEN
        value: "Fb2e570ac64e04418bbdc5b1c67ada554S"

  - type: static
    name: prefeitura-digital-frontend
    env: static
    region: ohio
    plan: free
    publishPath: frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: pserv
    name: mysql-db
    env: docker
    dockerContext: .
    dockerfilePath: mysql.Dockerfile
    plan: free
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: "rootpassword"
      - key: MYSQL_DATABASE
        value: "leopoldina"
      - key: MYSQL_USER
        value: "admin"
      - key: MYSQL_PASSWORD
        value: "adminpassword"
